package com.nbfc.service;

import java.util.List;

import com.nbfc.model.CGTMSECheckerForBatchApprovalAndRejectionSumbission;
import com.nbfc.model.CGTMSECheckerForBatchApprovalAndRejectionSumbissionSave;

public interface CGTMSECheckerForBatchApprovalAndRejectionService {
	public boolean storeData(CGTMSECheckerForBatchApprovalAndRejectionSumbissionSave cgtmseCheckerForBatchApprovalAndRejectionSumbissionSave);
	public boolean checkerApprove(CGTMSECheckerForBatchApprovalAndRejectionSumbissionSave cgtmseCheckerForBatchApprovalAndRejectionSumbissionSave,String userId);
	public boolean checkerRejected(CGTMSECheckerForBatchApprovalAndRejectionSumbissionSave cgtmseCheckerForBatchApprovalAndRejectionSumbissionSave);
	public List<CGTMSECheckerForBatchApprovalAndRejectionSumbission> getDataForNBFCCheckerFileDownLoad(CGTMSECheckerForBatchApprovalAndRejectionSumbission cgtmseCheckerForBatchApprovalAndRejectionSumbission);
	
}
